[devices]
[[devices.computers]]
    mac = "06-5D-EE-06-18-8A"
    ip = "10.10.0.100"
[[devices.computers]]
    mac = "06-5D-EE-06-18-8B"
    ip = "10.10.0.200"
[[devices.switches]]
    mac = "06-5D-EE-06-18-AA"
[[devices.routers]]
    mac = "06-5D-EE-06-18-BB"
    ip = "10.10.0.1"